title: Ramesh Wasantha
logo: /assets/img/propic.png
description:  Hi👋  I'm a Linux Enthusiast
show_downloads: false
theme: jekyll-theme-minimal
social:
  linkedin: https://www.linkedin.com/in/wasantha94/
  credly: https://www.credly.com/users/ramesh-wasantha/badges
  #youtube: https://www.youtube.com/@WolfTech_

