title: Ramesh Wasantha
logo: /assets/img/propic.png
description:  Hi! I’m an experienced System Administrator skilled in system administration, network configuration, and troubleshooting. I focus on improving system reliability, security, and efficiency.I enjoy solving problems and staying updated on new technologies. With strong communication and teamwork skills, I deliver solutions that help businesses succeed.Thanks for visiting my portfolio. Let's work together to achieve your IT goals.
show_downloads: false
theme: jekyll-theme-minimal


