title: Ramesh Wasantha
logo: /assets/img/propic.png
description:  Hello! I’m an experienced System Administrator with a passion for optimizing complex IT infrastructures. Specializing in system administration, network configuration, and troubleshooting, I am dedicated to enhancing system reliability, security, and efficiency.
I thrive on proactive problem-solving and continuously stay updated on emerging technologies. Known for effective communication and collaboration, I deliver innovatie soutions that drive business success.
Thank you for visiting my portfolio. I look forward to contributing to your business's success. 
show_downloads: false
theme: jekyll-theme-minimal


