title: Ramesh Wasantha
logo: /assets/img/propic.png
description:  Hi👋  I'm a Linux Enthusiast
show_downloads: false
theme: jekyll-theme-minimal
social:
  linkedin: https://www.linkedin.com/in/your-profile
  youtube: https://www.youtube.com/channel/your-channel-id

