title: Ramesh Wasantha
logo: /assets/img/propic.png
description:  Hi👋  I'm a Linux Enthusiast
show_downloads: false
theme: jekyll-theme-minimal
social:
  linkedin: https://www.linkedin.com/in/your-profile
  youtube: https://www.youtube.com/channel/your-channel-id
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ramesh-wasantha.github.io" # the base hostname & protocol for your site

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
